// app/src/store/authSlice.ts
// Redux slice that manages all authentication state.
// Defines the state shape, reducers (actions), and selectors.

import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import type { RootState } from './index';

// ── State shape ──────────────────────────────────────────────

interface AuthUser {
  sub: string; // Cognito unique user ID (UUID)
  email: string; // User's email from Google
}

interface AuthState {
  isAuthenticated: boolean;
  isLoading: boolean; // true while checking for an existing session on app mount
  user: AuthUser | null;
  error: string | null;
}

const initialState: AuthState = {
  isAuthenticated: false,
  isLoading: true, // starts true — the app checks for a session before rendering content
  user: null,
  error: null,
};

// ── Slice definition ─────────────────────────────────────────

const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    loginStart(state) {
      state.isLoading = true;
      state.error = null;
    },
    loginSuccess(state, action: PayloadAction<AuthUser>) {
      state.isAuthenticated = true;
      state.isLoading = false;
      state.user = action.payload;
      state.error = null;
    },
    loginFailure(state, action: PayloadAction<string>) {
      state.isAuthenticated = false;
      state.isLoading = false;
      state.user = null;
      state.error = action.payload;
    },
    logout(state) {
      state.isAuthenticated = false;
      state.isLoading = false;
      state.user = null;
      state.error = null;
    },
  },
});

// ── Action creators (auto-generated by createSlice) ──────────

export const { loginStart, loginSuccess, loginFailure, logout } =
  authSlice.actions;

// ── Selectors (used by components via useSelector) ───────────

export const selectIsAuthenticated = (state: RootState) =>
  state.auth.isAuthenticated;
export const selectAuthUser = (state: RootState) => state.auth.user;
export const selectAuthLoading = (state: RootState) => state.auth.isLoading;
export const selectAuthError = (state: RootState) => state.auth.error;

export default authSlice.reducer;
