// app/src/store/dataSourcesSlice.ts
// Redux slice managing data source state with Supabase persistence.
// Uses createAsyncThunk for CRUD operations via the data sources service.

import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import type { RootState } from './index';
import * as dataSourcesService from '../services/dataSourcesService';

// ── Types ────────────────────────────────────────────────────

export interface ApiCredentials {
  apiKey: string;
  apiSecret: string;
}

export interface DataSource {
  id: string; // UUID, generated by Supabase (gen_random_uuid)
  platformId: string; // Matches PlatformDef.id, or 'custom'
  customPlatformName?: string; // Only set when platformId === 'custom'
  displayName: string; // User-facing name, defaults to platform name
  credentials: ApiCredentials | null;
  createdAt: string; // ISO timestamp
}

interface DataSourcesState {
  sources: DataSource[];
  loading: boolean;
  error: string | null;
}

// ── Initial state ────────────────────────────────────────────

const initialState: DataSourcesState = {
  sources: [],
  loading: false,
  error: null,
};

// ── Async thunks ─────────────────────────────────────────────

export const fetchDataSources = createAsyncThunk(
  'dataSources/fetchAll',
  async () => {
    return dataSourcesService.fetchAll();
  },
);

export const createDataSource = createAsyncThunk(
  'dataSources/create',
  async (input: Omit<DataSource, 'id' | 'createdAt'>, { getState }) => {
    const state = getState() as RootState;
    const userId = state.auth.user?.sub;
    if (!userId) throw new Error('User not authenticated');
    return dataSourcesService.create(input, userId);
  },
);

export const updateDataSource = createAsyncThunk(
  'dataSources/update',
  async ({
    id,
    changes,
  }: {
    id: string;
    changes: Partial<Omit<DataSource, 'id' | 'createdAt'>>;
  }) => {
    return dataSourcesService.update(id, changes);
  },
);

export const deleteDataSource = createAsyncThunk(
  'dataSources/delete',
  async (id: string) => {
    await dataSourcesService.remove(id);
    return id;
  },
);

// ── Slice definition ─────────────────────────────────────────

const dataSourcesSlice = createSlice({
  name: 'dataSources',
  initialState,
  reducers: {
    clearDataSourcesError(state) {
      state.error = null;
    },
  },
  extraReducers: (builder) => {
    // ── Fetch all ──
    builder
      .addCase(fetchDataSources.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchDataSources.fulfilled, (state, action) => {
        state.loading = false;
        state.sources = action.payload;
      })
      .addCase(fetchDataSources.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message ?? 'Failed to load data sources';
      });

    // ── Create ──
    builder
      .addCase(createDataSource.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(createDataSource.fulfilled, (state, action) => {
        state.loading = false;
        state.sources.push(action.payload);
      })
      .addCase(createDataSource.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message ?? 'Failed to create data source';
      });

    // ── Update ──
    builder
      .addCase(updateDataSource.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(updateDataSource.fulfilled, (state, action) => {
        state.loading = false;
        const idx = state.sources.findIndex((s) => s.id === action.payload.id);
        if (idx !== -1) {
          state.sources[idx] = action.payload;
        }
      })
      .addCase(updateDataSource.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message ?? 'Failed to update data source';
      });

    // ── Delete ──
    builder
      .addCase(deleteDataSource.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(deleteDataSource.fulfilled, (state, action) => {
        state.loading = false;
        state.sources = state.sources.filter((s) => s.id !== action.payload);
      })
      .addCase(deleteDataSource.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message ?? 'Failed to delete data source';
      });
  },
});

// ── Action creators ──────────────────────────────────────────

export const { clearDataSourcesError } = dataSourcesSlice.actions;

// ── Selectors ────────────────────────────────────────────────

export const selectAllSources = (state: RootState) => state.dataSources.sources;

export const selectSourceById = (state: RootState, id: string) =>
  state.dataSources.sources.find((s) => s.id === id);

export const selectSourceCount = (state: RootState) =>
  state.dataSources.sources.length;

export const selectDataSourcesLoading = (state: RootState) =>
  state.dataSources.loading;

export const selectDataSourcesError = (state: RootState) =>
  state.dataSources.error;

export default dataSourcesSlice.reducer;
